apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@latest
  instanceProfile: Karpenter-pokefinder-eks-11e88d4c5a61f4b5424eaa96a7
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: pokefinder-eks
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: pokefinder-eks
